### ISSUE TITLE
MATLAB_LD_LIBRARY_PATH instead of LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by uzi0espil** [amarburg/docker-matlab-runtime#1]
First of all thanks for the nice Dockerfile explanation, I want to confirm whether importing matlab's exported python packages in such settings.. what I know is that matlab runtime looks for `LD_LIBRARY_PATH`? so how did you manage to make matlab looks for `MATLAB_LD_LIBRARY_PATH` instead?

**Comment by amarburg** [comment]
You're correct, any images based on this one need to explicitly append `MATLAB_LD_LIBRARY_PATH` to `LD_LBIRARY_PATH`.      What I found --- though I'll admit I didn't investigate too far --- was that the libraries provided by Matlab often conflicted with versions provided by the system leading to mysterious failures.

By leaving it to the user to manually add `MATLAB_LD_LIBRARY_PATH` to `LD_LIBRARY_PATH` they have better control of the side effects.

See for example [line 33 here](https://github.com/COVIS-Sonar/postprocessing/blob/master/Deploy/Dockerfile#L33)

**Comment by uzi0espil** [comment]
Actually I am facing the same problem you have said.. when I am changing `LD_LIBRART_PATH`, my c++ and python libraries failed because of dependency conflicts in shared libraries. So I though you have fixed it somehow with `MATLAB_LD_LIBRARY_PATH`. 

Thanks for the example you provided. Actually one of the conflicts is because of `libexpat.so`. What does `LD_PRELOAD` do in this [line](https://github.com/COVIS-Sonar/postprocessing/blob/master/Deploy/Dockerfile#L5):

**Comment by amarburg** [comment]
I believe it was an attempt to fix those conflicts by forcing `ld` to load the system `libexpat` first (before the Matlab version).   I don't recall if it was effective or if it's still doing anything.

The images based on this one run a mix of pure Python and Matlab-called-from-Python

**Comment by uzi0espil** [comment]
Thanks for your time and considerations.
